/**
 * Generate the rev-289 server packet table from the engine's own source.
 *
 * Hand-writing 69 opcode/length pairs is a transposed digit away from a stream
 * desync that only shows up under specific gameplay, so the table is generated
 * and committed, and this script doubles as a drift test: re-run it and diff.
 *
 * Cross-validated against the client's own baked-in length table, which is the
 * stronger check — that array is what the client actually frames with.
 *
 * Usage: node tools/gen-prot.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SERVER_ROOT = process.env.SWIFTKIT_SERVER_ROOT ?? resolve(import.meta.dirname, '../..');
const OUT = resolve(import.meta.dirname, '../src/shared/proto/rev289.gen.ts');
const REVISION = 289;

const src = (p) => readFileSync(resolve(SERVER_ROOT, p), 'utf8');

// The declarations are dead regular:
//   static readonly NAME = new ServerGameProt(id, length);
const DECL = /static readonly (\w+)\s*=\s*new ServerGame(?:Zone)?Prot\((-?\d+),\s*(-?\d+)\)/g;

function collect(text, into) {
    for (const [, name, id, len] of text.matchAll(DECL)) {
        const opcode = Number(id);
        if (into.has(opcode)) throw new Error(`duplicate opcode ${opcode}: ${into.get(opcode).name} vs ${name}`);
        into.set(opcode, { name, length: Number(len) });
    }
}

const prots = new Map();
collect(src('engine/src/network/game/server/ServerGameProt.ts'), prots);
collect(src('engine/src/network/game/server/ServerGameZoneProt.ts'), prots);

if (prots.size !== 69) throw new Error(`expected 69 prots, found ${prots.size}`);

// Cross-check against the client's own length table.
let clientChecked = 0;
const bundle = src('engine/public/client/client.js');
const arrays = bundle.match(/\[(?:\s*-?\d+\s*,){200,}\s*-?\d+\s*\]/g) ?? [];
const clientTable = arrays
    .map((a) => a.slice(1, -1).split(',').map(Number))
    .find((a) => a.length >= 256 && a[154] === 6);

const mismatches = [];
if (clientTable) {
    for (const [opcode, { name, length }] of prots) {
        if (clientTable[opcode] !== length) mismatches.push(`${name} (${opcode}): engine ${length}, client ${clientTable[opcode]}`);
        else clientChecked++;
    }
}

// Skill names, also taken from the client so indices cannot drift.
const namesMatch = bundle.match(/\["attack","defence"[^\]]*\]/);
if (!namesMatch) throw new Error('could not find the skill name table in the client bundle');
const skills = JSON.parse(namesMatch[0]);

const table = Array.from({ length: 256 }, (_, i) => {
    const p = prots.get(i);
    return p ? `    { name: '${p.name}', length: ${p.length} },` : '    null,';
});

const out = `// GENERATED by tools/gen-prot.mjs — do not edit.
// Source: engine ServerGameProt.ts + ServerGameZoneProt.ts at revision ${REVISION}.
// Re-run the generator and diff to detect protocol drift after pulling the engine.

export interface PacketDef {
    readonly name: string;
    /** Byte length; -1 means a u8 length prefix, -2 means u16. */
    readonly length: number;
}

export const REVISION = ${REVISION};

/** Indexed by opcode. null means the server never sends it at this revision. */
export const SERVER_PROT: ReadonlyArray<PacketDef | null> = [
${table.join('\n')}
];

/** Stat index -> name, from the client's own table. '-unused-' slots exist at this revision. */
export const SKILLS: ReadonlyArray<string> = ${JSON.stringify(skills)};
`;

if (process.argv.includes('--check')) {
    const current = readFileSync(OUT, 'utf8');
    if (current !== out) {
        console.error('DRIFT: generated table differs from the committed one. Re-run without --check.');
        process.exit(1);
    }
    console.log(`prot table up to date (${prots.size} prots, ${clientChecked} cross-checked)`);
} else {
    writeFileSync(OUT, out);
    console.log(`wrote ${OUT}`);
}

console.log(`prots: ${prots.size}`);
console.log(`client cross-check: ${clientTable ? `${clientChecked}/${prots.size} match` : 'client table not found — SKIPPED'}`);
if (mismatches.length) {
    console.log(`MISMATCHES (${mismatches.length}):`);
    for (const m of mismatches) console.log('  ' + m);
}
console.log(`skills: ${skills.filter((s) => s !== '-unused-').length} real of ${skills.length}`);
console.log(`UPDATE_STAT: opcode 154, length ${prots.get(154)?.length}`);
